### ISSUE TITLE
パッケージについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/todo#1]
# sqlite3やmysqlなどのDBのパッケージ

```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"　//これはなんのパッケージ?

	_ "github.com/mattn/go-sqlite3"//DBのsqlite3のパッケージ?
)
```

# 質問1
importの後に関数がないが無関数をインポートしている?

# 質問２
```go
"github.com/jinzhu/gorm"　//これはなんのパッケージ?

_ "github.com/mattn/go-sqlite3"//DBのsqlite3のパッケージ?　先頭の_は何?
```

# 質問３
純粋に気になったのですがgithub.comの先頭にかかれてることが多いのですか？

**Comment by totsumaru** [comment]
github.com... から始まっているimportは、goの標準パッケージには入っていないもの(外部パッケージ)です。
標準パッケージとは、goのインストールと同時についてくるもので、基本的な機能しかありません。

いろいろな機能を使う場合は、誰かがgithubにあげた外部パッケージを使う必要があり、それはほぼ全てgithub上にあります。
そのため、github.com...から始まるimport文を使用します。

ちなみに、`_`から始まっているimportは、importするけど直接使わないものです。
ではなぜそれをimportする必要があるのかというと、それをimportしておかないと、別のimportしたパッケージが動かない可能性があるからです。

2つセットでimportする必要がある場合に多いので、覚えておきましょう！

参考記事を添付します。
https://qiita.com/ogady/items/0cedd3599c4dc13e9a95
